# Generated by Django 5.1.2 on 2024-10-14 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steamfake', '0006_curso_turma_alter_aluno_nota1_alter_aluno_nota2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='steamfake.curso'),
        ),
    ]
