# Generated by Django 5.1.2 on 2024-10-14 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('steamfake', '0008_delete_aluno_delete_categoria_remove_turma_curso_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=23, unique=True)),
            ],
        ),
    ]
